global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: prediction_market_bot
    metrics_path: /metrics
    static_configs:
      - targets:
          - prediction-market-ui:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prediction-market-ui
