apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-bot-data
  namespace: prediction-market
  labels:
    app.kubernetes.io/part-of: prediction-market-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
